import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import '../styles/globals.scss'
import '@nextcss/reset';
import styles from './layout.module.scss';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.html}>
      <body className={styles.main}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
